
services:
  fastapi-app:
    build: .
    container_name: fastapi-container
    ports:
      - "8000:8000"
    volumes:
      - .:/app # Bind mount the current directory to /app in the container
    environment:
      - ENV=development # Example: Pass environment variables
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
